### ISSUE TITLE
make_metadata.py is missing

### ISSUE THREAD

**Issue by liuyuer** [EmilJunker/python-saml-idp#1]
Where is the make_metadata.py?

**Comment by EmilJunker** [comment]
You need to install the packages listed in `.devcontainer/requirements.txt`. The make_metadata.py script will come with that.

Edit: To be precise, the make_metadata.py script is part of the pysaml2 library located here: https://github.com/IdentityPython/pysaml2/blob/master/src/saml2/tools/make_metadata.py

**Comment by EmilJunker** [comment]
@liuyuer I hope you were able to find the script, generate the metadata successfully and start the application.

I'm closing this issue now. Feel free to post a comment or open a new issue if you have any more questions.
